config/routes.rb
Rails.application.routes.draw do
  root to: "static#home"

  #resources :users

  get "/signup", to: "users#new", as: "signup" #signup_path or signup_url
  post "/signup", to: "users#create"

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy", as: "logout"

  resources :users, only: [] do
    resources :blogs 
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #index
  #get "/blogs", to: "blogs#index", as: "blogs"

  #new/create
  #get "/blogs/new", to: "blogs#new", as: "new_blog"
  #post "/blogs", to: "blogs#create"

  #show
  #get "/blogs/:id", to: "blogs#show", as: "blog"

  #edit/update
  #get "/blogs/:id/edit", to: "blogs#edit", as: "edit_blog"
  #patch "/blogs/:id", to: "blogs#update"

  #destroy
  #delete "/blogs/:id", to: "blogs#destroy"
end

# first argument is the route we want to give it, second argument is a key value, this will go to the folder, then run the index.html.erb
# RESTful Routes index, show, new, create edit update destroy

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy

    scope :published, -> { where.not(published_date: nil) }
    scope :recent_published_blogs, -> { self.published.where("published_date > ?", 5.days.ago) }
    scope :not_published, -> { where(published_date: nil) }
    scope :sorted_published_blogs, -> { self.published.order(published_date: :desc) }
    scope :sorted_non_published_blogs, -> { self.non_published.order(published_date: :desc) }
    scope :search, -> (term) { self.published.where("title LIKE ?", "%#{term}%")}

    validates_presence_of :title, :content
    validates_uniqueness_of :title

end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :published_blog
    has_many :users, through: :published_blog

    def create
        @blog = Blog.find(params[:blog_id])
        @comment = @blog.comments.create! (params[:comment])
        redirect_to @blog
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :blogs
    has_many :comments

    validates :email, presence: true, uniqueness: true
    has_secure_password

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

helper_method :current_user, :logged_in? 

    private
        def current_user
            User.find_by_id(session[:user_id]) if logged_in?
        end

        def logged_in?
            !!session[:user_id]
        end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

    before_action :set_blog, except: [:index, :new, :create]

    def index 
        if params[:term] 
            @blogs = Blog.search(params[:term])
        else
            @blogs = Blog.sorted_published_blogs 
        end
    end

    def show #/blogs/:id
        #@blog = Blog.find_by_id(params[:id])
    end

    def new
        @blog = Blog.new
    end

    def create
        @blog = current_user.blogs.build(blog_params)
        if @blog.save
            redirect_to user_blogs_path(current_user)
        else
            render :new
        end
    end

    def edit #/blogs/:id/edit
        @blog = Blog.find_by_id(params[:id])
    end

    def update #patch /blogs/:id
        if @blog.update(blog_params)
            redirect_to user_blog_path(current_user, @blog) #_path - route helper /blogs/id
        else
            render :edit
        end
    end

    def destroy #delete /blogs/:id
        @blog.destroy
        redirect_to user_blogs_path(current_user)
    end

    private

        def set_blog
            @blog = Blog.find_by_id(params[:id])
        end

        def blog_params
            params.require(:blog).permit(:title, :content, :published_date, :author, :mood)
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    belongs_to :blog

    def create 
        @blog = Blog.find(params[:blog_id])
            @comment = @blog.comments.create(params[:comment].permit(:name, :comment))
        redirect_to blog_path(@blog)
    end

    def destroy
        @blog = Blog.find(params[:post_id])
        @comment = @blog.comments.find(params[:id])
        @comment.destroy
        redirect_to blog_path(@blog)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.find_by_email(user_params[:email])

        if @user && @user.authenticate(user_params[:password])
            session[:user_id] = @user.id
            redirect_to root_path
        else
            render :new
        end
    end
    
    def destroy
        session.clear
        redirect_to root_path
    end

    private
        def user_params
            params.require(:user).permit(:email, :password)
        end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
            
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else
            render :new
        end
    end

    private
        def user_params
            params.require(:user).permit(:email, :password)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_for([current_user, blog]) do |f| %> <!-- f is for form builder -->
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <br> 

    <div>
        <%= f.label :content %><br>
        <%= f.text_area :content, :cols => 30, :rows => 10 %>
    </div>
    <br>

    <div>
        <%= f.label :published_date %>
        <%= f.date_field :published_date%>
    </div>
    <br> 

    <div>
        <%= f.label :author %>
        <%= f.text_field :author %>
    </div>
    <br>

    <div>
        <%= f.label :mood %>
        <%= f.text_field :mood %>
    </div>
    <br>

    <%= f.submit button_name %>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit <%= @blog.title %></h1>

<%= render(partial: 'blogs/form', locals: { blog: @blog, button_name: "Update Post" }) %>

app/views/blogs/index.html.erb
<h1>Mommy Minute Blog!</h1>

<%= form_tag(user_blogs_path(current_user), method: "get") do %> 
        <%= text_field_tag :term, nil, id: "Search", placeholder: "enter search term" %>
    <%= submit_tag "Search"%>
<%end%>

<% @blogs.each do |blog| %>
    <div>
        <h3><%= link_to blog.title %></h3>
        <p><%= blog.published_date %></p>
    </div>
    <div class="comment-count">
        <%= blog.comments.count %>
    </div>
<% end %>

app/views/blogs/new.html.erb
<h1> Mommy Minute! </h1>

<%= render(partial: 'blogs/form', locals: { blog: @blog, button_name: "Create Post" }) %>

app/views/blogs/show.html.erb
<h1><%= @blog.title %></h1>
<p>Published: <%= @blog.published_date ? @blog.published_date : "Not Published" %></p>

<p><%= @blog.content %></p>

<h2>Comments</h2>
<% @blog.comments.each do |c| %>
    <p>
    <b><%= c.name %> said:</b><br>
    <%= time_ago_in_words(c.created_at) %> ago 
    </p>

    <p>
    <%= c.body %>
    </p>
<% end %>

<% form_for [@blog, Comment.new] do |f| %>
    <p>
        <%= f.label :name, "Author" %><br>
        <%= f.text_field :name %><br>
        <%= f.label :body, "Comment Description" %><br>
        <%= f.text_area :body %><br>
    </p>
    <p>
    <%= f.submit "Add Comment" %>
<% end %>

<p><%= link_to "Edit", edit_blog_path(@blog) %></p>


<p><%= link_to "Delete", blog_path(@blog), method: "delete" %></p>

app/views/comments/_comment.html.erb
<%= comment.name %>
<%= comment.comment%>

<%= link_to "Delete", [comment.blog, comment], method: :delete, { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MommyMinute</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav>
  <ul>
    <!-- Neutral Links -->
    <li><%= link_to "Home", root_path %></li>
  
    <% unless logged_in? %>
      <li><%= link_to "Signup", signup_path %></li>
      <li><%= link_to "Login", login_path %></li>
    <% else %>
      <li><%= link_to "Mommy Minute Blogs", user_blogs_path(current_user) %></li>
      <li><%= link_to "Create Mommy Minute", new_user_blog_path(current_user) %></li>
      <li><%= link_to "Logout", logout_path, method: "delete" %></li>
    <% end %>
    
    
  </ul>
  </nav>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Signup</h1>

<%= form_for @user, url: signup_path do |f| %>
    <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div><br>
    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div><br>

    <%= f.submit "Signup" %>
<% end %>